version: '2.2'

# z jakich serwisów skłąda się system, nazwa serwisu to jest nazwa z networkingu
services: 
    myredis:
        image: 'redis:alpine'
    mypostgres:
        image: 'postgres:alpine'
        environment: 
            - POSTGRES_PASSWORD=karol123
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres 
        volumes: 
            - C:/Code/DevOps/project_game_rental/game_rental_postgres:/var/lib/postgressql/data
        # ports:
        #     - "6432:5432"
    mybackend:
        build:
            dockerfile: Dockerfile
            context: './game_rental_backend'
        volumes: 
              #bookmark - "zostaw folder taki jaki jest" -> tego katalogu nie ruszaj
            - /opt/app/node_modules
              #zeby widział ze sa zmiany w kodzie podczas developmentu, mapuje biezacy na wewnętrzny
            - C:/Code/DevOps/project_game_rental/game_rental_backend:/opt/app

        environment: 
            - POSTGRES_PASSWORD=karol123
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres 
            - REDIS_HOST=myredis
            - POSTGRES_HOST=mypostgres
    myfrontend:
        build:
            dockerfile: Dockerfile
            context: './game-rental-frontend'
        environment: 
            CHOKIDAR_USEPOLLING: 'true'
        volumes: 
            - /opt/app/node_modules
            - C:/Code/DevOps/project_game_rental/game-rental-frontend/:/opt/app
        # ports: 
        #     - "3000:3000"
    mynginx:
        restart: always
        build: 
            dockerfile: Dockerfile
            context: './game_rental_nginx'
        ports: 
            - '9090:80'